# Find all the available rules by running:
# swiftlint rules
#

# rule identifiers to exclude from running
disabled_rules:
    - valid_docs
    - force_try
    - todo
    - trailing_whitespace
    - type_name
    - large_tuple
    - redundant_optional_initialization
    - empty_parentheses_with_trailing_closure
    - cyclomatic_complexity
    - superfluous_disable_command
    - identifier_name
    - weak_delegate

    #- force_cast

    #- operator_whitespace
    #- vertical_whitespace
    #- variable_name
    #- function_parameter_count
    #- type_body_length
    #- operator_whitespace
    #- colon
    #- comma
    #- control_statement


# paths to ignore during linting. Takes precedence over `included`.
excluded:
    - Carthage
    - Sumo/Code/Utilities/Drawer/DrawerView.swift

# configurable rules can be customized from this configuration file
file_length:
    warning: 500
    error: 1000
line_length:
    warning: 260
    error: 400
type_body_length:
    warning: 300
    error: 500
function_body_length:
    warning: 100
    error: 150
variable_name:
    max_length:
        warning: 50
        error: 80
nesting:
    type_level:
        warning: 4
        error: 6
    statement_level:
        warning: 5
        error: 10
