name: Dummy

############
# Options
############

options:
  bundleIdPrefix: at.stefanhaider
  groupSortPosition: top

############
# Packages
############

packages:
  Fetch:
    url: https://github.com/allaboutapps/Fetch
    majorVersion: 2.0.0
  ReactiveSwift:
    url: https://github.com/ReactiveCocoa/ReactiveSwift
    majorVersion: 6.0.0
  DataSource:
    url: https://github.com/allaboutapps/DataSource
    majorVersion: 8.0.0
  netfox:
    url: https://github.com/upstreammobility/netfox
    majorVersion: 1.20.0
  DataEngine:
    url: https://mgmt.upstream-mobility.at/bitbucket/scm/dat/ios.git
    branch: "master"

############
# Configs
############

configs:
  Debug: debug
  Test: debug
  Stage: debug
  Release: release

options:
  transitivelyLinkDependencies: false

############
# Include
############

include:
  - path: xcodegen/dummy.yml
    relativePaths: false
